name: BUILD IMAGE
on:
  push:
    branches:
      - main
      - 'releases/**'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Docker login
        run: |
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image and
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api-test:latest -f build/Dockerfile .

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/api-test:latest